version: '{build}'

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
          PYTHON: "C:\\Python34-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install codecov --user

build_script:
  - ./gradlew assemble --no-daemon
test_script:
  - ./gradlew check --no-daemon

on_success:
  - ./gradlew jacocoTestReport --no-daemon
  - python -m codecov -f build\reports\jacoco\test\jacocoTestReport.xml -F windows

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper